/**
 * One-time TOTP recovery codes.
 *
 * The least-complex secure 2FA recovery for EduCBT: at the moment two-step
 * verification is enabled, the account is issued a set of one-time codes.
 * Each code substitutes for a single authenticator prompt at stage 2 (and
 * forces a password change), then it is dead. Lost codes are regenerated by
 * the account holder after re-authenticating; for locked-out school users
 * the office reset path remains (a reset clears the password, not the
 * authenticator).
 *
 * Storage rule, same as sessions and reset tokens: only the SHA-256 of each
 * code is persisted. The plaintext exists exactly once, on the confirmation
 * screen, and is never logged, emailed or stored.
 *
 * The table is FORCED row-level secured (rls.sql): writes happen inside the
 * account's own tenant transaction (or the platform-admin policies for
 * platform accounts); stage-2 consumption runs with the session-user GUC set
 * (verifySecondFactor).
 */

import { createHash, randomInt } from 'node:crypto';
import { and, eq, isNull, sql } from 'drizzle-orm';
import { db, schema, forSchool } from '@/db';

// Crockford-style alphabet without vowels and confusables: dictation-safe.
const ALPHABET = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';

export const RECOVERY_CODE_COUNT = 8;

function generateCode(): string {
  let out = '';
  for (let i = 0; i < 10; i++) {
    out += ALPHABET[randomInt(ALPHABET.length)];
    if (i === 4) out += '-'; // XXXXX-XXXXX: easy to read aloud, hard to mistype
  }
  return out;
}

export function hashCode(code: string): string {
  return createHash('sha256').update(code.trim().toLowerCase()).digest('hex');
}

/** Delete any existing codes and issue a fresh set. Returns plaintext ONCE. */
export async function issueRecoveryCodes(
  session: { id: number; schoolId: number | null },
): Promise<string[]> {
  const codes = Array.from({ length: RECOVERY_CODE_COUNT }, generateCode);
  const rows = codes.map((code) => ({
    userId: session.id,
    schoolId: session.schoolId,
    codeHash: hashCode(code),
  }));

  const write = async (tx: Parameters<Parameters<typeof forSchool>[1]>[0]) => {
    await tx.delete(schema.totpRecoveryCodes).where(eq(schema.totpRecoveryCodes.userId, session.id));
    await tx.insert(schema.totpRecoveryCodes).values(rows);
  };

  if (session.schoolId) {
    await forSchool(session.schoolId, write);
  } else {
    await db.transaction(async (tx) => write(tx));
  }

  return codes;
}

/** How many codes remain unused — for the account security screen. */
export async function remainingRecoveryCodes(
  session: { id: number; schoolId: number | null },
): Promise<number> {
  const count = async (tx: Parameters<Parameters<typeof forSchool>[1]>[0]) => {
    const [row] = await tx
      .select({ n: sql<number>`count(*)::int` })
      .from(schema.totpRecoveryCodes)
      .where(
        and(
          eq(schema.totpRecoveryCodes.userId, session.id),
          isNull(schema.totpRecoveryCodes.usedAt),
        ),
      );
    return row?.n ?? 0;
  };

  if (session.schoolId) return forSchool(session.schoolId, count);
  return db.transaction(async (tx) => count(tx));
}

/** Clear every code — called when two-step verification is disabled. */
export async function clearRecoveryCodes(
  session: { id: number; schoolId: number | null },
): Promise<void> {
  const clear = async (tx: Parameters<Parameters<typeof forSchool>[1]>[0]) => {
    await tx.delete(schema.totpRecoveryCodes).where(eq(schema.totpRecoveryCodes.userId, session.id));
  };

  if (session.schoolId) {
    await forSchool(session.schoolId, clear);
  } else {
    await db.transaction(async (tx) => clear(tx));
  }
}
