import type { HelpArticle } from '../types';

/**
 * Examinations. Sources verified against the running code:
 *   question bank   src/app/portal/questions/** (BankFields, BulkImport, parsers.ts, actions.ts), src/lib/exam/sets.ts
 *   approvals       src/app/portal/exams/approvals/page.tsx, reviewSet() in src/lib/exam/sets.ts
 *   papers          src/app/portal/exams/[seriesId]/page.tsx, src/lib/exam/compose.ts
 *   timetable       src/app/portal/timetable/page.tsx, src/lib/exam/timetable.ts
 *   invigilation    src/app/portal/invigilation/page.tsx, src/lib/exam/invigilate.ts
 *   sessions        src/app/portal/invigilate/**, src/lib/exam/sessions.ts
 *   marking         src/app/portal/marking/**, src/lib/exam/marking-overview.ts
 */
export const examinations: HelpArticle[] = [
  {
    slug: 'how-an-examination-works',
    category: 'examinations',
    title: 'How an Examination Works, Start to Finish',
    description: 'The whole journey from writing questions to marked scripts, and who does each part.',
    keywords: ['exam', 'examination', 'process', 'overview', 'steps', 'workflow', 'life cycle', 'from start to finish'],
    audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'],
    where: 'Examination office',
    popular: true,
    icon: 'exam',
    blocks: [
      { type: 'p', text: 'Every examination follows the same path. Knowing the order helps you see why a step is sometimes blocked: each step needs the one before it.' },
      { type: 'table', head: ['Step', 'Who', 'Where'], rows: [
        ['1. Write questions', 'Subject teachers', '*Writing Questions in the Question Bank*'],
        ['2. Submit for review', 'Subject teachers', 'Question bank, **Submit for review**'],
        ['3. Approve or send back', 'Principal, Vice Principal, Examination Officer', '*Approving Question Sets*'],
        ['4. Compose papers', 'Examination office', '*Creating, Scheduling and Publishing Papers*'],
        ['5. Schedule and publish', 'Examination office', '*Creating, Scheduling and Publishing Papers*'],
        ['6. Build the timetable and invigilation roster', 'Examination office', '*The Examination Timetable*, *Invigilation Schedule*'],
        ['7. Students sit the papers', 'Students', 'Their own timetable'],
        ['8. Watch sittings and mark written answers', 'Invigilators, teachers', '*Test and Exam Sessions: Watching and Reattempts*, *Marking Written (Theory) Answers*'],
      ] },
      { type: 'note', text: 'Only **approved** questions can go into a paper. A set that is still being written, or is waiting for review, does not count.' },
    ],
    related: ['writing-questions', 'approving-question-sets', 'papers-schedule-publish'],
  },
  {
    slug: 'writing-questions',
    category: 'examinations',
    title: 'Writing Questions in the Question Bank',
    description: 'Choose the subject and class, then add questions by typing, pasting or importing a file.',
    keywords: ['exam questions', 'exam', 'question bank', 'add question', 'paste questions', 'csv', 'import', 'objective', 'theory', 'marks', 'questions', 'excel', 'format guide'],
    audience: ['teacher', 'exam_officer', 'principal', 'vice_principal'],
    where: 'Questions',
    popular: true,
    icon: 'exam',
    blocks: [
      { type: 'p', text: 'Questions live in a **set**: one set per subject, class level and exam type. The fields at the top decide which set you are working in, so choose them first. Changing any of them reloads the page onto the matching set.' },
      { type: 'steps', title: 'Start a set', items: [
        'Open **Questions**.',
        'Check the banner that says **Writing for:**. It names the examination your questions will go into.',
        'Choose the **Subject** and the **Class Level** (the class list unlocks once a subject is chosen).',
        'Choose the **Exam Type**: objective or theory.',
        'Choose the **Delivery Mode** (CBT or Written) if it is shown. Some examinations fix this for every subject, and then the choice is replaced by a note saying so.',
        'Set **Default Marks** for the questions you are about to add.',
        'Pick a **Method** to add questions: **Manual Entry**, **Paste in Format** or **CSV / Excel Import**.',
      ] },
      { type: 'h', text: 'Paste in Format' },
      { type: 'p', text: 'Open **Format Guide** under the box to see the pattern. For objective questions each question is numbered, has options A to D, then an answer line and optional marks:' },
      { type: 'list', items: [
        '`1. What is the capital of Nigeria?`',
        '`A) Lagos`  `B) Abuja`  `C) Kano`  `D) Port Harcourt`',
        '`ANSWER: B`',
        '`MARKS: 2`',
      ] },
      { type: 'p', text: 'Theory questions are a numbered question followed by `MARKS:`. Select **Parse & Preview**, tick the questions you want to keep, then add them. Any that could not be read are listed with the reason, so nothing is dropped silently.' },
      { type: 'h', text: 'CSV / Excel Import' },
      { type: 'list', items: [
        'Objective columns: `question, option_a, option_b, option_c, option_d, correct_option, marks`.',
        'Theory columns: `question, marks, marking_guide`.',
        'A downloadable template is offered on the import screen. Start from it so the headings match.',
      ] },
      { type: 'warning', text: 'Questions are only accepted while the examination office has the question window open. If the window is closed, or the examination is not the one you meant, you will be told. Ask the exam office rather than trying again.' },
    ],
    related: ['submitting-questions', 'approving-question-sets', 'how-an-examination-works'],
  },
  {
    slug: 'submitting-questions',
    category: 'examinations',
    title: 'Submitting Your Questions for Review',
    description: 'Send a finished set to the exam office, and what happens if it is sent back.',
    keywords: ['exam questions', 'exam', 'submit', 'submit for review', 'minimum questions', 'sent back', 'returned', 'revision', 'written intent', 'paired'],
    audience: ['teacher'],
    where: 'Questions',
    icon: 'exam',
    blocks: [
      { type: 'steps', title: 'Submit a set', items: [
        'Make sure the set has at least the **minimum number of questions** the exam office requires. If you are short, EduCBT tells you how many you have against how many are needed.',
        'Select **Submit for review**.',
        'The set now waits for the exam office. You cannot edit it while it waits.',
      ] },
      { type: 'note', text: 'For a terminal examination, the objective set and the theory set for the same subject and class are submitted **together**. If one half is short or not started, neither can go. The message names which half is short.' },
      { type: 'h', text: 'Written examinations' },
      { type: 'p', text: 'When a subject is sat on paper, you do not type the questions in. Use **Submit Written Intent** instead. Depending on how the examination was set up, this is either approved straight away or goes to the exam office for approval.' },
      { type: 'h', text: 'If a set is sent back' },
      { type: 'p', text: 'The exam office must give a reason when it sends a set back, and you will see that comment. Correct the questions it mentions and submit again.' },
    ],
    related: ['writing-questions', 'approving-question-sets'],
  },
  {
    slug: 'approving-question-sets',
    category: 'examinations',
    title: 'Approving Question Sets',
    description: 'Review what teachers submitted, approve it, or send it back with a reason.',
    keywords: ['approve exam questions', 'exam', 'approve', 'approval', 'review', 'send back', 'reject', 'return', 'approve questions', 'minimum', 'backup', 'restore'],
    audience: ['principal', 'vice_principal', 'exam_officer'],
    where: 'Examinations  Approve Questions',
    icon: 'exam',
    blocks: [
      { type: 'p', text: 'Only the Principal, Vice Principal and Examination Officer can review question sets. Teachers cannot, even for their own subject.' },
      { type: 'steps', title: 'Review a set', items: [
        'Open **Approve Questions**. The table lists every submission with its **Teacher**, **Subject**, **Class**, **Type**, **Delivery**, **Status** and **Submitted** date.',
        'Use the filters to narrow by subject, mode, type or class.',
        'Select **Review Obj.** or **Review Th.** to open the objective or theory set.',
        'Read the questions, then **approve** the set, or **send it back** with a comment.',
      ] },
      { type: 'warning', text: 'A set is approved or sent back **as a whole**. If you send it back you must write a reason of at least 10 characters, because a rejection without a reason cannot be acted on.' },
      { type: 'h', text: 'Other tools on this page' },
      { type: 'list', items: [
        '**Save requirement** sets how many questions a teacher must write before a set can be submitted. It applies to new sets; a set already in progress keeps the requirement it started with.',
        '**Back up question bank now** saves a copy on demand, and **Restore missing questions** brings back any that have gone missing.',
        'A submission that should never have been made can be deleted from the table.',
      ] },
    ],
    related: ['submitting-questions', 'papers-schedule-publish'],
  },
  {
    slug: 'papers-schedule-publish',
    category: 'examinations',
    title: 'Creating, Scheduling and Publishing Papers',
    description: 'Compose papers from approved questions, give them dates, then publish to students.',
    keywords: ['exam papers', 'create examination', 'exam', 'compose', 'papers', 'publish', 'schedule examination', 'sitting window', 'slots', 'practice', 'ca test', 'not ready to publish'],
    audience: ['principal', 'vice_principal', 'exam_officer'],
    where: 'Examinations',
    popular: true,
    icon: 'exam',
    blocks: [
      { type: 'p', text: 'Open an examination from the **Examinations** list. Its page walks you through three steps in order: **Compose papers**, **Schedule examination**, then **Publish**.' },
      { type: 'steps', title: 'Prepare and release an examination', items: [
        'Under **Compose papers**, check the **Questions available** table. Each paper needs the stated number of approved objective questions per student.',
        'Select **Compose papers**. A paper is created for every subject and class with enough approved questions.',
        'Under **Schedule examination**, enter the **First day of sitting** and **Last day of sitting**, then schedule. Papers are placed on school days, in up to four slots a day (two by default: morning and afternoon).',
        'Under **Publish**, read the checklist. When every item is satisfied, select **Publish examination**.',
      ] },
      { type: 'note', text: 'A subject without enough approved questions is never composed silently. It is named on the page and skipped, and it will **not** be sat. Composing again never creates duplicate papers.' },
      { type: 'warning', text: 'Publishing is blocked until every paper has a timetable slot and a sitting window exists. The sitting window is enforced: no student can start before it opens or after it closes. One class never sits two papers at once.' },
      { type: 'h', text: 'Practice examinations' },
      { type: 'p', text: 'A practice examination has no timetable. Once published, students can sit it any time, and it never counts towards their results.' },
      { type: 'h', text: 'Deleting by mistake' },
      { type: 'p', text: 'Only a draft examination, one that was never composed or published, can be deleted. Once papers exist, or it has been published, it is closed or cancelled instead, so scores and attempts are never lost.' },
    ],
    related: ['exam-timetable', 'invigilation-schedule', 'approving-question-sets'],
  },
  {
    slug: 'exam-timetable',
    category: 'examinations',
    title: 'The Examination Timetable',
    description: 'Build, review, print and send the timetable to class teachers.',
    keywords: ['exam timetable', 'exam', 'timetable', 'schedule', 'generate', 'regenerate', 'notify class teachers', 'print', 'working draft', 'date', 'venue', 'duration'],
    audience: ['principal', 'vice_principal', 'exam_officer', 'teacher', 'student', 'parent'],
    where: 'Timetable',
    icon: 'exam',
    blocks: [
      { type: 'h', text: 'For the examination office' },
      { type: 'steps', title: 'Build and send', items: [
        'Open **Timetable** and choose the examination under **Choose examination**.',
        'In **Build and send**, set the **First day of sitting** and **Last day of sitting**, then select **Generate**. This composes any newly approved papers and then lays every paper out across the window.',
        'Review the table: **Date**, **Day**, **Time**, **Subject**, **Class**, **Duration**, **Access Code** and **Invigilator**.',
        'To move one paper, change its **Date & time**, **Duration (min)** or **Venue** and select **Save slot**.',
        'Select **Notify class teachers** to tell each class teacher once about their class timetable.',
      ] },
      { type: 'warning', text: 'Generating again **overwrites every paper\'s date and time**. Use it to rebuild, not to tweak one paper; use **Save slot** for that.' },
      { type: 'note', text: 'Until the examination is published, the timetable is a **working draft**. Publish it from the exam office to release it to teachers and set the sitting window the system enforces.' },
      { type: 'h', text: 'For teachers, students and parents' },
      { type: 'p', text: 'You see the published timetable. If it has not been released you will see "The examination timetable has not been released yet" and you will be notified when it is. Parents see the timetable for each linked child; if no child is linked to the account, the page says so.' },
      { type: 'p', text: 'Use your browser\'s print command to print the timetable on the school letterhead. The buttons and filters do not appear on the printed copy.' },
    ],
    related: ['papers-schedule-publish', 'invigilation-schedule'],
  },
  {
    slug: 'invigilation-schedule',
    category: 'examinations',
    title: 'Invigilation Schedule',
    description: 'Assign invigilators to papers, manage access codes, and see your own duties.',
    keywords: ['exam invigilation', 'exam', 'invigilation', 'invigilator', 'duty roster', 'access code', 'hall', 'assign', 'release code', 'regenerate code', 'download pdf', 'timetable changed'],
    audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'],
    where: 'Invigilation',
    icon: 'exam',
    blocks: [
      { type: 'h', text: 'For the examination office' },
      { type: 'steps', title: 'Build the roster', items: [
        'Open **Invigilation** and choose the examination, then select **Show**.',
        'If nobody is assigned yet, select **Create invigilation schedule**. EduCBT assigns everyone automatically, spreading the load and keeping a teacher away from their own subject.',
        'Change anyone afterwards by choosing a name in the **Invigilator** column and selecting **Set**.',
        'If some papers could not be covered, select **Fill any gaps automatically**.',
        'Select **Download PDF** to print the roster.',
      ] },
      { type: 'h', text: 'Rules EduCBT enforces' },
      { type: 'list', items: [
        'A subject teacher never invigilates their own paper. You will see "A subject teacher never invigilates their own paper."',
        'A teacher cannot be in two halls at the same time. For a CBT hall where one invigilator watches two papers from one room, use **Anyway** to override.',
      ] },
      { type: 'h', text: 'If the timetable changes' },
      { type: 'p', text: 'If papers move after the roster was built, the page shows **The schedule no longer matches the timetable** and lists each problem (a paper with no invigilator, or a clash). Select **Apply the timetable changes** to settle them.' },
      { type: 'h', text: 'Access codes' },
      { type: 'list', items: [
        '**Generate** creates a code for a paper. Regenerating a code stops the old one **immediately**.',
        '**Release** marks the code as released to the hall. A code must be generated before it can be released.',
      ] },
      { type: 'h', text: 'For teachers' },
      { type: 'p', text: 'You see **My Invigilation Duties**: every paper assigned to you, with date and time, subject, class, duration, access code and hall. You cannot change assignments. If a duty is impossible, see the exam office.' },
    ],
    related: ['exam-timetable', 'test-and-exam-sessions'],
  },
  {
    slug: 'test-and-exam-sessions',
    category: 'examinations',
    title: 'Test and Exam Sessions: Watching and Reattempts',
    description: 'Watch a live sitting, give extra time, force-submit, and grant a reattempt.',
    keywords: ['exam sessions', 'exam', 'sessions', 'live', 'watch', 'extra time', 'extend', 'force submit', 'reattempt', 'power cut', 'flags', 'quiet', 'invigilate'],
    audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'],
    where: 'Test/Exam Sessions',
    icon: 'exam',
    blocks: [
      { type: 'p', text: 'This page shows who is sitting right now. To look up anyone\'s history, search by **Name or admission number** and use the **Subject** and **Status** filters. School-wide roles search everyone; a teacher sees only the subjects they teach.' },
      { type: 'steps', title: 'Watch a live sitting', items: [
        'Open **Test/Exam Sessions**. Sittings in progress are listed.',
        'Select **Watch** on the paper. You can open the live board if you are school-wide staff, the paper\'s invigilator, or its subject teacher.',
        'The board shows each candidate\'s state (**Not started**, **Writing**, **Submitted**), how many questions they have **Answered**, **Time left**, and any flags.',
        'A candidate with no activity for 2 minutes is marked **quiet**.',
      ] },
      { type: 'h', text: 'Extra time' },
      { type: 'list', items: [
        'For one candidate: enter minutes and a reason, then select **Extend**. Extra time must be between 1 and 120 minutes.',
        'For the whole hall (for example after a power cut): use **Give the whole hall extra time**, then **Add to every writing candidate**.',
        'A reason is always required, because unexplained extra time cannot be told apart from favouritism.',
      ] },
      { type: 'h', text: 'Force submit' },
      { type: 'p', text: 'If a candidate walks out, enter a reason and select **Force submit**. Their saved answers are marked as they stand.' },
      { type: 'h', text: 'Granting a reattempt' },
      { type: 'p', text: 'If a session ended unfairly, the Principal, Vice Principal or Examination Officer can let the student sit again. Teachers cannot.' },
      { type: 'steps', items: [
        'Find the student\'s session in the table.',
        'Type the reason in **Why? (required)**.',
        'Select **Grant reattempt**.',
      ] },
      { type: 'warning', text: 'A reattempt **clears the earlier answers and score** and starts the clock again. It is only possible for a session that has finished (submitted, auto-submitted, expired or cancelled), never one still in progress.' },
    ],
    related: ['invigilation-schedule', 'marking-written-answers'],
  },
  {
    slug: 'marking-written-answers',
    category: 'examinations',
    title: 'Marking Written (Theory) Answers',
    description: 'For teachers: award marks to written answers. For the exam office: see marking progress.',
    keywords: ['exam marking', 'exam', 'marking', 'mark', 'theory', 'award', 'marking guide', 'marking status', 'waiting', 'ca progress', 'reopen results'],
    audience: ['teacher', 'principal', 'vice_principal', 'exam_officer'],
    where: 'Marking',
    icon: 'exam',
    blocks: [
      { type: 'h', text: 'For teachers' },
      { type: 'p', text: 'Your **Marking** page lists written answers waiting on you, for the subjects you teach. Objective questions are marked automatically, so only theory answers appear here.' },
      { type: 'steps', title: 'Award marks', items: [
        'Open **Marking**. The heading tells you how many answers are waiting.',
        'Read the question, the **Guide** (if the question has one) and the student\'s answer. If they left it blank you will see "No answer given."',
        'Enter the mark in the box labelled **Marks (max N)**. Half marks are allowed.',
        'Select **Award**. You will see "Marked."',
      ] },
      { type: 'list', items: [
        'The mark must be between 0 and the question\'s maximum.',
        'You can only mark scripts for a class and subject you are assigned to teach.',
        'Only scripts that have been submitted appear. A sitting still in progress does not.',
      ] },
      { type: 'warning', text: 'If a student\'s results for the term have already been reviewed, published or locked, marks cannot be changed until the results are reopened. EduCBT will say "Reopen reviewed, published or locked results before correcting examination marks."' },
      { type: 'h', text: 'For the examination office' },
      { type: 'p', text: 'Your page is **Marking Status**, a school-wide overview with three parts:' },
      { type: 'list', items: [
        '**Marking status by teacher**: how many written answers each teacher still has **Waiting**, by subject.',
        '**CA assessment progress by teacher**: how many assessment components each teacher has recorded this term. Filter by teacher or subject and select **Apply**; **Clear** resets. The **Status** is **Not Started**, **In Progress** or **All Recorded**.',
        '**Completed exams, marking status**: for each sat paper, how many theory answers are marked out of the total.',
      ] },
    ],
    related: ['test-and-exam-sessions', 'how-an-examination-works'],
  },
];
