import type { HelpArticle } from '../types';

/**
 * Getting Started and Troubleshooting. Order of set-up follows the real
 * dependencies in the code: a student needs a class and a current session;
 * a result needs assessment components, a grading scale and a ranking policy;
 * a paper needs approved questions and a sitting window.
 */
export const gettingStarted: HelpArticle[] = [
  {
    slug: 'welcome',
    category: 'getting-started',
    title: 'Welcome to EduCBT',
    description: 'What EduCBT is for and the main things you can do in it.',
    keywords: ['welcome', 'introduction', 'what is educbt', 'overview', 'about', 'cbt', 'computer based test'],
    audience: ['all'],
    icon: 'flag',
    popular: true,
    blocks: [
      { type: 'p', text: 'EduCBT is your school\'s place for examinations and academic records. Teachers write questions, the exam office turns approved questions into timetabled papers, students sit them on a computer, and results flow into report cards that parents can see once the Principal publishes them.' },
      { type: 'list', items: [
        '**Run examinations**: question bank, approval, papers, timetable, invigilation, live sittings and marking.',
        '**Record results**: continuous-assessment scores, compiled results, broadsheets and report cards.',
        '**Manage the school**: students, staff, classes, subjects, sessions and terms.',
        '**Stay in touch**: notifications, announcements and messages.',
      ] },
      { type: 'note', text: 'Each school has its own web address. Use the address your school gave you; it is how EduCBT knows which school you belong to.' },
      { type: 'p', text: 'What you can see depends on your role. Start with *Understanding Your Dashboard and Menu* to find your way around.' },
    ],
    related: ['your-dashboard', 'quick-start', 'signing-in'],
  },
  {
    slug: 'quick-start',
    category: 'getting-started',
    title: 'Getting Started With Your School',
    description: 'The order to set up a new school so nothing is blocked along the way.',
    keywords: ['quick start', 'set up', 'setup', 'new school', 'onboarding', 'first steps', 'begin', 'getting started', 'checklist'],
    audience: ['principal', 'vice_principal', 'exam_officer'],
    where: 'School Settings, Staff, Classes, Students',
    popular: true,
    icon: 'flag',
    blocks: [
      { type: 'p', text: 'Each step depends on the one before it, so follow the order. The Principal does the first and third steps; other office roles can help with the rest.' },
      { type: 'steps', title: 'Set up your school', items: [
        '**School profile.** Under **School Settings**, add the school name, address, contacts and crest. They appear on report cards.',
        '**Session and term.** Add your academic session and set the current term. Students cannot be enrolled until the school has a current session.',
        '**Assessments and grading.** Define the assessment components (they must total 100, with one exam component), the grading scale and the ranking policy. Results cannot be compiled without them.',
        '**Staff.** Add teachers and office staff under **Staff**, then assign class teachers and subject teachers.',
        '**Classes and subjects.** Create classes under **Classes** and subjects under **Subjects**. Students need a class to be enrolled in.',
        '**Students.** Add students one by one or import a class from a file, then link their parents.',
        '**Subject registration.** Class teachers confirm which subjects each student takes, since papers and results only include registered subjects.',
        '**Examinations.** Teachers write questions, the office approves them, then composes, schedules and publishes papers.',
      ] },
      { type: 'warning', text: 'Set the assessment components before teachers start recording scores. Once they are in use, their keys and maximums can no longer be changed.' },
    ],
    related: ['school-settings', 'managing-staff', 'adding-a-student', 'how-an-examination-works'],
  },
  {
    slug: 'cannot-see-a-feature',
    category: 'troubleshooting',
    title: 'I Cannot See a Menu Item or Feature',
    description: 'Why something from a guide may be missing from your menu.',
    keywords: ['cannot see', 'missing', 'menu', 'not there', 'no access', 'permission', 'role', 'not found', '404', 'hidden', 'sidebar'],
    audience: ['all'],
    icon: 'wrench',
    blocks: [
      { type: 'p', text: 'EduCBT only shows what your role is allowed to use. A missing item usually means your role does not include it.' },
      { type: 'steps', title: 'Check these in order', items: [
        'Look at *Understanding Your Dashboard and Menu* to see which items your role has.',
        'If you are a teacher, check that the school office has **assigned** you. **Record scores**, **Marking** and the question bank for a class only work for classes and subjects you are assigned to teach. **My students**, **Remarks** and **Signature** appear only if you are a **class teacher**.',
        'Approving questions, publishing results, committing promotion and changing school settings are limited to the Principal or office roles.',
        'If the page says it cannot be found, you probably opened a page for another role. Go back to your dashboard.',
        'If you believe your role is wrong, ask the school office to check your assignment under **Staff**.',
      ] },
    ],
    related: ['your-dashboard', 'managing-staff'],
  },
  {
    slug: 'sign-in-problems',
    category: 'troubleshooting',
    title: 'I Cannot Sign In',
    description: 'A step-by-step check when your sign-in is refused.',
    keywords: ['cannot sign in', 'cant login', 'cannot log in', 'wrong password', 'locked out', 'account locked', 'no school at this address', 'login failed', 'paused', 'suspended'],
    audience: ['all'],
    popular: true,
    icon: 'wrench',
    blocks: [
      { type: 'steps', title: 'Work through these in order', items: [
        '**Check the address.** Use your own school\'s EduCBT address. If you see "No school at this address", the address is wrong or not linked to an active school.',
        '**Check your sign-in ID.** Staff and students each have an ID issued by the school. For a student it is the student ID.',
        '**Check your password.** Use the eye icon to see what you typed. New accounts use the temporary password the school gave you.',
        '**Wait if you are paused.** After five wrong passwords in a row the account pauses briefly, and the pause grows with each further failure, up to an hour. Wait, then try again with the right password.',
        '**Use password recovery** if you have forgotten it. See *Forgot Password*.',
        '**Two-factor code?** If two-factor security is on, you will be asked for a 6-digit code after your password. See *My Two-Factor Code Is Not Working*.',
        '**Still stuck?** Ask the school office. They can check whether your account is active and issue a new password.',
      ] },
      { type: 'note', text: 'A student whose account has been deactivated or withdrawn cannot sign in until the office reactivates them.' },
    ],
    related: ['signing-in', 'forgot-password', 'two-factor-problems', 'password-problems'],
  },
  {
    slug: 'password-problems',
    category: 'troubleshooting',
    title: 'Password Problems',
    description: 'Reset emails not arriving, expired links, and being asked to change your password.',
    keywords: ['password', 'reset link', 'email not arriving', 'expired', 'link expired', 'must change password', 'set your password', 'temporary password', 'new password rejected', 'minimum'],
    audience: ['all'],
    icon: 'wrench',
    blocks: [
      { type: 'table', head: ['What you see', 'What to do'], rows: [
        ['The reset email never arrives', 'Check spam. Reset emails need the school\'s email delivery switched on and a recovery email on your account. If nothing comes, ask the school office to issue a new password.'],
        ['The reset link does not work', 'Each link works once and expires after 30 minutes. Request a new one.'],
        ['**Set your password** appears after signing in', 'This is normal for a new or reset account. Choose your own password to continue.'],
        ['The new password is refused', 'It must be at least 8 characters and different from your current one.'],
        ['You have no recovery email', 'The school office can issue a new temporary password in person.'],
      ] },
    ],
    related: ['forgot-password', 'changing-your-password', 'recovery-email'],
  },
  {
    slug: 'two-factor-problems',
    category: 'troubleshooting',
    title: 'My Two-Factor Code Is Not Working',
    description: 'What to try when your authenticator code is refused, or you have lost your phone.',
    keywords: ['2fa not working', 'code not working', 'invalid code', 'lost phone', 'lost authenticator', 'recovery code', 'authenticator', 'two factor problem', 'time', 'new phone'],
    audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'],
    icon: 'wrench',
    blocks: [
      { type: 'steps', title: 'Try these in order', items: [
        'Make sure you are reading the code for **this** account. Authenticator apps hold many.',
        'Type the current 6-digit code promptly. It changes every 30 seconds, so wait for a fresh one if it is about to change.',
        'Check your phone\'s clock is set automatically. These codes depend on the time being right.',
        'If you set it up by typing the key, confirm the app was set to *Time-based*, *6 digits*, *30 seconds*.',
        'No phone? On the code screen select **Lost your authenticator? Use a recovery code** and enter one of the codes EduCBT showed you when you turned two-factor on (format `XXXXX-XXXXX`). Each works once.',
      ] },
      { type: 'warning', text: 'Recovery codes were shown only once. If you have none left and cannot use your authenticator, ask the school office for help with your account.' },
    ],
    related: ['two-factor-authentication', 'sign-in-problems'],
  },
  {
    slug: 'missing-data',
    category: 'troubleshooting',
    title: 'A Student, Subject or Result Is Missing',
    description: 'Common reasons something you expect is not showing.',
    keywords: ['missing', 'student missing', 'not showing', 'no students', 'subject missing', 'result missing', 'not listed', 'empty', 'no results', 'pending approval'],
    audience: ['principal', 'vice_principal', 'exam_officer', 'teacher', 'parent', 'student'],
    icon: 'wrench',
    blocks: [
      { type: 'table', head: ['Missing', 'Check'], rows: [
        ['A student is not on the roster', 'Change the status filter (it may be set to Active). A student added by a teacher or by import stays **Pending Approval** until the office approves them.'],
        ['A student is not on a score sheet', 'The student must be registered for that subject in that class. See *Managing Subjects and Subject Registration*.'],
        ['A student has no paper', 'See *My Examination Does Not Appear*.'],
        ['A teacher has no classes', 'The office must assign them under **Staff** as a subject teacher or class teacher.'],
        ['Results are not visible to a student or parent', 'Results show only once the Principal has **published** them. For a parent, results must also be shared with that account.'],
        ['No children appear for a parent', 'The office must link the parent to the student. See *Linking a Parent or Guardian*.'],
      ] },
    ],
    related: ['editing-a-student', 'managing-subjects', 'how-results-are-published'],
  },
  {
    slug: 'exam-not-appearing',
    category: 'troubleshooting',
    title: 'My Examination Does Not Appear',
    description: 'Why a paper may not be available to a student, and what the office should check.',
    keywords: ['exam not appearing', 'paper missing', 'no paper', 'cannot start exam', 'exam not showing', 'publish', 'sitting window', 'access code', 'not published', 'not registered'],
    audience: ['student', 'teacher', 'principal', 'vice_principal', 'exam_officer'],
    popular: true,
    icon: 'wrench',
    blocks: [
      { type: 'h', text: 'For students' },
      { type: 'list', items: [
        'Only subjects you are **registered for** appear. Ask your class teacher to check your subject registration.',
        'A paper can only be started **inside its sitting window**. Before it opens or after it closes you cannot start it.',
        'The paper may need an **access code** from the invigilator, read out when the paper starts.',
        'If you were cut off unfairly, tell the invigilator. The office can grant a reattempt.',
      ] },
      { type: 'h', text: 'For the examination office' },
      { type: 'steps', title: 'Check, in order', items: [
        'Was the examination **published**? Publishing is blocked until every paper has a timetable slot and a sitting window.',
        'Does the subject have **enough approved questions**? A subject without them is skipped when composing and is not sat.',
        'Is the student **registered** for the subject?',
        'Is the paper **cancelled** or already **closed**?',
      ] },
    ],
    related: ['papers-schedule-publish', 'managing-subjects', 'what-students-see'],
  },
  {
    slug: 'school-access-problems',
    category: 'troubleshooting',
    title: 'School Access Problems',
    description: 'When the whole school address does not work for you.',
    keywords: ['school access', 'address', 'wrong school', 'no school at this address', 'subdomain', 'school suspended', 'cannot reach', 'url', 'link'],
    audience: ['all'],
    icon: 'wrench',
    blocks: [
      { type: 'steps', title: 'Check', items: [
        'Make sure you typed the exact address your school gave you. Each school has its own.',
        'If EduCBT says "No school at this address", the address is not linked to an active school. Confirm it with your school office.',
        'Try another device or network, in case the page was blocked or cached.',
        'If it is working for others but not for you, the problem is with your account. See *I Cannot Sign In*.',
      ] },
      { type: 'note', text: 'If your whole school cannot reach EduCBT, ask the school office to contact the platform administrator.' },
    ],
    related: ['sign-in-problems', 'signing-in'],
  },
];
