import type { HelpArticle } from '../types';

/**
 * School Management. Sources verified against the running code:
 *   students       src/app/portal/students/**, src/lib/people/students.ts
 *   staff          src/app/portal/staff/**, src/lib/people/staff.ts (STAFF_ROLES)
 *   classes        src/app/portal/classes/**
 *   subjects       src/app/portal/subjects/**, src/app/portal/registration/**
 *   settings       src/app/portal/settings/**, src/app/portal/NewTermDialog.tsx
 *   sidebar/roles  src/app/portal/PortalShell.tsx, SchoolDashboard.tsx, TeacherDashboard.tsx
 */
export const schoolManagement: HelpArticle[] = [
  {
    slug: 'adding-a-student',
    category: 'school-management',
    title: 'Adding a Student',
    description: 'Register one student, or import a whole class from a file.',
    keywords: ['add student', 'register student', 'enrol', 'new student', 'admission number', 'student id', 'import', 'csv', 'template', 'passport photo', 'pending approval'],
    audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'],
    where: 'Students',
    popular: true,
    icon: 'school',
    blocks: [
      { type: 'steps', title: 'Register one student', items: [
        'Open **Students** and expand **Register a student**.',
        'Optionally add a passport photo.',
        'Leave **Student ID** blank to have one generated, or type your own. It is also the student\'s login username.',
        'Enter **First name**, **Surname**, **Sex**, **Date of birth** and the **Class**. First name, surname and class are required.',
        'Optionally add the guardian\'s details. This sends the parent an invitation to create their own portal account.',
        'Select **Register student**.',
      ] },
      { type: 'p', text: 'The admission number and first password are generated automatically. The first password is the student\'s **surname in lowercase**, padded with zeros to at least 8 characters, and the student must change it at first sign-in. EduCBT shows you the login and initial password once, so note them down.' },
      { type: 'note', text: 'Admission numbers follow the pattern **PREFIX/YY/0001**, where the prefix is your school\'s ID prefix and YY is the two-digit year. A custom Student ID must not already belong to another student or another login.' },
      { type: 'h', text: 'If you are a class teacher' },
      { type: 'p', text: 'The record is created and placed in your class, but it stays **pending** until the school office approves it. You can only place students into a class you head.' },
      { type: 'h', text: 'Import many students' },
      { type: 'steps', items: [
        'Under **Import many students**, select **Download template**.',
        'Fill it in. There are only four columns: `first_name`, `last_name`, `gender`, `date_of_birth`. Do not add admission numbers or passwords; they are generated.',
        'Choose the class in **Into class**, choose your file, and select **Import students**.',
      ] },
      { type: 'list', items: [
        'The file must be under about 1 MB and can hold at most **500 students** at a time. Split larger lists.',
        'The header row must include `first_name` and `last_name`.',
        'Imported students are pending the office\'s approval.',
      ] },
    ],
    related: ['editing-a-student', 'student-status-and-password', 'linking-a-parent'],
  },
  {
    slug: 'editing-a-student',
    category: 'school-management',
    title: 'Finding and Editing a Student',
    description: 'Search the roster, change a record, and move a student to another class.',
    keywords: ['edit student', 'search student', 'filter', 'move class', 'change class', 'student record', 'my students', 'capacity', 'approve student', 'pending'],
    audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'],
    where: 'Students',
    icon: 'school',
    blocks: [
      { type: 'steps', title: 'Find a student', items: [
        'Open **Students**. Use the search box, then **Search**, or filter by class and by status (**Active**, **Suspended**, **Pending Approval**, **Withdrawn**, **Expelled** or **All**) and select **Filter**.',
        'Select **Edit** on the row to change it there, or **View profile** to open the full record.',
      ] },
      { type: 'steps', title: 'Edit a record', items: [
        'Change the photo, Student ID, names, sex, class, parent details or address.',
        'Select **Save changes**.',
      ] },
      { type: 'note', text: 'Moving a student to another class changes their enrolment for the **current session only**. Past sessions are untouched. A class that is full refuses the move: "That class has reached its capacity."' },
      { type: 'h', text: 'Approving students' },
      { type: 'p', text: 'When teachers add students, a **Pending office actions** panel appears on the office Overview. Select **Review pending**, then **Approve** to activate and enrol each student. Only the school office can approve.' },
      { type: 'h', text: 'If you are a class teacher' },
      { type: 'p', text: 'You can open **My Students** to see the students of the class you head. If you see "You are not the class teacher of any class", the school office assigns that under **Staff**.' },
    ],
    related: ['adding-a-student', 'student-status-and-password'],
  },
  {
    slug: 'student-status-and-password',
    category: 'school-management',
    title: 'Suspending, Withdrawing and Resetting a Student\'s Password',
    description: 'Change a student\'s standing or reset their password. Office staff only.',
    keywords: ['deactivate', 'withdraw', 'suspend', 'reactivate', 'reinstate', 'reset student password', 'standing', 'expelled', 'graduated', 'student locked out'],
    audience: ['principal', 'vice_principal', 'exam_officer'],
    where: 'Students  student profile',
    icon: 'school',
    blocks: [
      { type: 'p', text: 'Only the school office can change a student\'s standing. Open the student\'s profile and use the **Standing** and **Password** sections.' },
      { type: 'table', head: ['Action', 'What it does'], rows: [
        ['**Deactivate**', 'The student loses portal access until reactivated. Use it for suspension, unpaid fees and similar cases.'],
        ['**Withdraw**', 'Use when a student leaves the school. Their results are kept.'],
        ['**Reactivate** / **Reinstate**', 'Gives access back to a suspended or withdrawn student.'],
      ] },
      { type: 'steps', title: 'Reset a student\'s password', items: [
        'Open the student\'s profile.',
        'Under **Password**, select **Reset password** and confirm.',
      ] },
      { type: 'p', text: 'The password goes back to the student\'s surname in lowercase, padded with zeros to at least 8 characters. Their existing sessions are signed out, and they must choose a new password at the next sign-in.' },
    ],
    related: ['editing-a-student', 'password-problems'],
  },
  {
    slug: 'linking-a-parent',
    category: 'school-management',
    title: 'Linking a Parent or Guardian',
    description: 'Connect a parent to a student so they can see the child\'s results and timetable.',
    keywords: ['parent', 'guardian', 'link', 'invite', 'invitation', 'relationship', 'results visible', 'family'],
    audience: ['principal', 'vice_principal', 'exam_officer'],
    where: 'Students  student profile  Guardians',
    icon: 'school',
    blocks: [
      { type: 'steps', title: 'Link a guardian', items: [
        'Open the student\'s profile and go to **Guardians**.',
        'Enter the guardian\'s **name**, and an **email** or a **phone number** (at least one is required).',
        'Choose the relationship: parent, guardian, mother, father or other.',
        'Decide whether this guardian can see the child\'s results.',
        'Select **Link guardian**.',
      ] },
      { type: 'p', text: 'If a guardian with the same email or phone already exists, they are linked rather than duplicated, so one parent can follow several children. A new guardian receives an invitation link to create their own account.' },
      { type: 'note', text: 'If results are not shared with a guardian, they see: "Results for this child are not shared with this account. The school office can change this."' },
    ],
    related: ['adding-a-student', 'what-parents-see'],
  },
  {
    slug: 'managing-staff',
    category: 'school-management',
    title: 'Managing Staff',
    description: 'Add staff, choose their role, and assign them the classes and subjects they teach.',
    keywords: ['add staff', 'add teacher', 'staff', 'teacher', 'role', 'staff id', 'assign teacher', 'class teacher', 'subject teacher', 'reset staff password', 'remove staff', 'reactivate staff', 'principal'],
    audience: ['principal', 'vice_principal'],
    where: 'Staff',
    popular: true,
    icon: 'school',
    blocks: [
      { type: 'steps', title: 'Add a staff member', items: [
        'Open **Staff** and use **Add a staff member**.',
        'Enter the **Title**, **First name** and **Surname** (the names are required), and optionally the sex, email, phone and a passport photo.',
        'Choose the **Role**: Teacher, Examination Officer, Vice Principal or Principal.',
        'Leave the staff ID blank to have one generated, or type your own.',
        'Save. EduCBT shows the login and a **temporary password** once. The person must change it at first sign-in.',
      ] },
      { type: 'warning', text: 'A school has one Principal. To hand the role to someone else you must transfer it, and the current Principal becomes a Vice Principal. A school with no Principal cannot approve or publish results, so the only Principal cannot be removed until another is chosen.' },
      { type: 'h', text: 'Assign teaching duties' },
      { type: 'p', text: 'Being a "teacher" does not by itself give access to any class. Under **Assign teaching duties**, choose what you are assigning:' },
      { type: 'list', items: [
        '**Subject teachers** teach specific subjects to specific classes. This is what lets them record scores, mark and write questions for those classes.',
        '**Class teachers** head a class. This is what gives them **My Students**, **Remarks** and **Signature**.',
      ] },
      { type: 'steps', items: [
        'Choose the **Teacher**.',
        'Select the **Classes** and, for subject teachers, the **Subjects**.',
        'Save. Anything that could not be assigned is explained rather than skipped silently.',
        'To undo one, select **Drop** beside the assignment and confirm.',
      ] },
      { type: 'h', text: 'Passwords, leaving and returning' },
      { type: 'list', items: [
        'Open **Edit** on a staff member to change details or the **Staff ID**, or to reset their password. Resetting stops the current password working immediately and shows a new temporary one.',
        'Standing a staff member down keeps their record and history. Only staff marked as having left can be **Reactivated**.',
      ] },
    ],
    related: ['managing-classes', 'managing-subjects', 'password-problems'],
  },
  {
    slug: 'managing-classes',
    category: 'school-management',
    title: 'Managing Classes',
    description: 'Create classes by level and arm, set capacity, and see class teachers.',
    keywords: ['classes', 'create class', 'level', 'arm', 'capacity', 'department', 'class teacher', 'jss', 'ss'],
    audience: ['principal', 'vice_principal'],
    where: 'Classes',
    icon: 'school',
    blocks: [
      { type: 'steps', title: 'Create classes', items: [
        'Open **Classes** and find **Create classes**.',
        'Enter the **Level**, for example the year group.',
        'In **Arms**, list the arms separated by commas (for example `A, B, C`) to create every arm of that level at once.',
        'Choose a **Department** if the level uses one, and set a **Capacity** if you want to limit the size.',
        'Save.',
      ] },
      { type: 'p', text: 'The table lists each **Class**, its **Class teacher** and the number of **Students**. Use **Edit** to change a class\'s arm, department or capacity, then **Save changes**.' },
      { type: 'note', text: 'Once a class is full, EduCBT refuses to place more students in it ("That class has reached its capacity"). Raise the capacity first if you need to.' },
      { type: 'p', text: 'Teachers who are not the Principal or Vice Principal see **My Teaching Assignments** here instead, which lists only their own classes.' },
    ],
    related: ['managing-staff', 'adding-a-student', 'managing-subjects'],
  },
  {
    slug: 'managing-subjects',
    category: 'school-management',
    title: 'Managing Subjects and Subject Registration',
    description: 'Add subjects, mark them compulsory, and register students for their subjects.',
    keywords: ['subjects', 'add subject', 'compulsory', 'standard subject list', 'junior', 'senior', 'department', 'subject registration', 'register subjects', 'taught by'],
    audience: ['principal', 'vice_principal', 'teacher'],
    where: 'Subjects, Subject Registration',
    icon: 'school',
    blocks: [
      { type: 'h', text: 'Subjects (Principal and Vice Principal)' },
      { type: 'steps', title: 'Add a subject', items: [
        'Open **Subjects**. You can start from the **Standard subject list**, or use **Add a subject**.',
        'Enter the **Subject name**. Leave **Code** as auto to have one generated.',
        'Choose the **Level** (Junior or Senior) and, if needed, a **Department**. Leave it as "None (open to all)" for a subject every student can take.',
        'Save.',
      ] },
      { type: 'p', text: 'The table shows each subject, whether it is **Compulsory**, and who it is **Taught by** (it says "nobody assigned" until a subject teacher is assigned under **Staff**). Filter it by assignment, level or department and select **Apply**.' },
      { type: 'h', text: 'Subject Registration (class teachers)' },
      { type: 'p', text: 'Results and papers only include a subject a student is registered for, so registration matters. Open **Subject Registration**, choose your class and select **Show**. Compulsory subjects are listed for the class, and each student\'s **Subjects registered** can be adjusted.' },
      { type: 'note', text: 'If you see "You are not the class teacher for any class, so there is nothing to register here", you have not been assigned a class. Ask the school office.' },
    ],
    related: ['managing-staff', 'managing-classes'],
  },
  {
    slug: 'school-settings',
    category: 'school-management',
    title: 'School Settings',
    description: 'School profile, session and term, assessments and grading, and signatures.',
    keywords: ['settings', 'school profile', 'crest', 'logo', 'session', 'term', 'grading', 'grade', 'assessment', 'components', 'ranking', 'signature', 'remark', 'new term', 'start new session'],
    audience: ['principal', 'vice_principal', 'exam_officer'],
    where: 'School Settings',
    popular: true,
    icon: 'school',
    blocks: [
      { type: 'note', text: 'Only the **Principal** can change school-wide settings. Other office roles can view them. Teachers keep access to their own signature and remarks.' },
      { type: 'h', text: 'School profile & branding' },
      { type: 'p', text: 'These details appear on report cards. Set the school name, the Principal\'s display name, phone, email, website and address. The **School crest** (PNG or JPEG, up to 2 MB) is also used as the faint watermark on printed documents. The school code is permanent and cannot be edited.' },
      { type: 'h', text: 'Session & term' },
      { type: 'list', items: [
        'Choose the **Academic session** and **Term**, then **Set current period**. Exams, scores and results are filed under these periods. Changing the current period **does not move existing records**.',
        'Use **Add a session** (for example `2026/2027`). Tick the box to make it current, starting with First Term.',
      ] },
      { type: 'steps', title: 'Start a new session or term (Principal)', items: [
        'On the Overview, select **Start New Session/Term**.',
        'Choose the **Academic session** and **Term** in the **Switch Session / Term** window.',
        'Select **Confirm**.',
      ] },
      { type: 'warning', text: 'This changes the dashboard for **all staff**. Past question banks stay accessible, and results and exams from the previous term are preserved.' },
      { type: 'h', text: 'Assessments & grading' },
      { type: 'list', items: [
        '**How a term is marked**: the assessment components (for example tests and exam), each with a name, key and maximum. They must total exactly **100**, with exactly one marked as the examination component.',
        '**Grading scale**: each grade has a minimum score; the maximum is the next band\'s minimum. Saving a change creates a new version.',
        '**Ranking policy**: how ties are shown (competition 1, 1, 3; dense 1, 1, 2; ordinal 1, 2, 3), the tiebreakers, and whether incomplete results are ranked.',
      ] },
      { type: 'warning', text: 'Once assessments are in use, the keys, maximums and which component is the exam cannot be changed, only the labels. Set them up carefully before teachers start recording scores.' },
      { type: 'h', text: 'Signatures & remarks' },
      { type: 'p', text: 'Each signing role (Principal, Class Teacher, Examination Officer) can draw a signature, type one, or upload an image of up to 2 MB, and set remark ranges that supply the default report-card comment for an average score band.' },
    ],
    related: ['report-cards', 'how-results-are-published'],
  },
  {
    slug: 'your-dashboard',
    category: 'getting-started',
    title: 'Understanding Your Dashboard and Menu',
    description: 'What each role sees after signing in, and where to find things.',
    keywords: ['dashboard', 'overview', 'menu', 'sidebar', 'navigation', 'cannot see', 'missing menu', 'role', 'permissions', 'who sees what'],
    audience: ['all'],
    where: 'Portal sidebar',
    popular: true,
    icon: 'flag',
    blocks: [
      { type: 'p', text: 'What you see depends on your role. If a menu item from this guide is not in your sidebar, your role does not include it. That is by design, not a fault.' },
      { type: 'table', head: ['Role', 'Menu areas'], rows: [
        ['Principal', 'School (Overview, Staff, Students, Classes, Subjects, Results, Broadsheet, Promotion, Transcripts, Activity log, School Settings), Examinations, Communications. Teaching too if also assigned to teach.'],
        ['Vice Principal', 'As the Principal, without Transcripts.'],
        ['Examination Officer', 'School (Overview, Staff, Students, Classes, Subjects, Results, Broadsheet, School Settings), Teaching, Examinations, Communications.'],
        ['Teacher', 'Teaching (Dashboard, Subject Registration, My assignments, Subject Results, Record scores), Examinations (Question Bank, Timetable, Invigilation Schedule, Test/Exam Sessions, Marking Status), Communications. Class teachers also get My students, Signature and Remarks.'],
        ['Student', 'Dashboard, My results, Practice, Notifications, Announcements.'],
        ['Parent', 'Dashboard, My children, Exam timetable, Notifications, Announcements, Messages.'],
      ] },
      { type: 'h', text: 'Office Overview' },
      { type: 'p', text: 'Principal, Vice Principal and Examination Officer see tiles for **Active students**, **Active staff** and **Active classes**, the current session and term, a **Pending office actions** panel when students await approval, and the **Results Pipeline** for each class. The Principal also has **Start New Session/Term**.' },
      { type: 'h', text: 'Teacher dashboard' },
      { type: 'p', text: 'Teachers see **Subject assignments**, **Classes headed**, **My students** and **To mark**, then **Record CA** (a shortcut to each score sheet), **Classes I Head**, a **Result Pipeline** if they head a class, a **Marking queue** and a link to the **Question Bank**.' },
      { type: 'h', text: 'Students and parents' },
      { type: 'p', text: 'Students see **Your papers** (with **Start** or **Resume**) and **Check results**. Parents see **My Children** with each child\'s class and published terms.' },
    ],
    related: ['quick-start', 'cannot-see-a-feature'],
  },
];
