import type { HelpFaq } from './types';

/**
 * Short answers. Each one restates something an article already verifies and
 * links to it, so the FAQ cannot say something the guides do not.
 */
export const FAQ_LIST: HelpFaq[] = [
  // Account
  { id: 'sign-in', group: 'account', question: 'How do I sign in?', answer: ['Open your school\'s own EduCBT address, enter the sign-in ID the school gave you and your password, then select Sign in. For a student the sign-in ID is the student ID.'], article: 'signing-in' },
  { id: 'forgot-password', group: 'account', question: 'What do I do if I forget my password?', answer: ['Select Forgot password? on the sign-in page. If your account has a recovery email, a one-time link is sent that expires after 30 minutes. If it has none, the school office can issue you a new password in person.'], article: 'forgot-password' },
  { id: 'change-password', group: 'account', question: 'How do I change my password?', answer: ['Select your name at the bottom of the portal sidebar, enter your current password and then your new one twice. The new password must be at least 8 characters and different from the old one.'], article: 'changing-your-password' },
  { id: 'two-factor', group: 'account', question: 'How does two-factor authentication work?', answer: ['It is optional. After your password, you also enter a 6-digit code from an authenticator app on your phone. It is available to the Principal, Vice Principal, Examination Officer and teachers.'], article: 'two-factor-authentication', audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'] },
  { id: 'lost-authenticator', group: 'account', question: 'What if I lose access to my authentication device?', answer: ['Use one of the 8 one-time recovery codes EduCBT showed you when you turned two-factor on. On the code screen, choose Lost your authenticator? Use a recovery code. If you have none left, ask the school office.'], article: 'two-factor-problems', audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'] },
  { id: 'locked', group: 'account', question: 'Why does my account say it is paused after wrong passwords?', answer: ['After five wrong passwords in a row the account pauses briefly. The pause grows with each further failure, up to an hour. Wait, then try again.'], article: 'sign-in-problems' },

  // School
  { id: 'add-student', group: 'school', question: 'How do I add a student?', answer: ['Open Students, expand Register a student, enter the first name, surname and class, and select Register student. The admission number and first password are generated for you. To add a whole class, use Import many students with the downloadable template (up to 500 rows).'], article: 'adding-a-student', audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'] },
  { id: 'student-pending', group: 'school', question: 'Why is a student I added still "pending"?', answer: ['Students added by a class teacher, or imported, wait for the school office to approve them. The office reviews them from the Pending office actions panel on the Overview.'], article: 'editing-a-student', audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'] },
  { id: 'add-teacher', group: 'school', question: 'How do I add a teacher?', answer: ['The Principal or Vice Principal opens Staff, uses Add a staff member, chooses the role Teacher and saves. EduCBT shows a temporary password once, and the teacher must change it at first sign-in.'], article: 'managing-staff', audience: ['principal', 'vice_principal'] },
  { id: 'assign-teacher', group: 'school', question: 'How do I assign a teacher to a class?', answer: ['Under Staff, use Assign teaching duties. Choose Class teachers to make someone head of a class, or Subject teachers to give them specific subjects in specific classes.'], article: 'managing-staff', audience: ['principal', 'vice_principal'] },
  { id: 'subjects', group: 'school', question: 'How do I manage subjects?', answer: ['The Principal or Vice Principal opens Subjects to add a subject, set its level and department, and see who teaches it. Class teachers confirm which subjects each student takes under Subject Registration.'], article: 'managing-subjects', audience: ['principal', 'vice_principal', 'teacher'] },
  { id: 'school-info', group: 'school', question: 'How do I update school information?', answer: ['The Principal opens School Settings and edits the School profile & branding tab: name, contacts, address and crest. These details appear on report cards.'], article: 'school-settings', audience: ['principal'] },
  { id: 'new-term', group: 'school', question: 'How do I start a new term?', answer: ['The Principal selects Start New Session/Term on the Overview, chooses the session and term and confirms. This changes the dashboard for all staff, and results and exams from the previous term are preserved.'], article: 'school-settings', audience: ['principal'] },

  // Examinations
  { id: 'submit-questions', group: 'examinations', question: 'How are questions submitted?', answer: ['Teachers write questions in the Question Bank for a subject, class and exam type, then select Submit for review once the set reaches the required minimum. For a terminal examination the objective and theory sets are submitted together.'], article: 'submitting-questions', audience: ['teacher', 'exam_officer', 'principal', 'vice_principal'] },
  { id: 'approve-questions', group: 'examinations', question: 'Who approves submitted questions?', answer: ['The Principal, Vice Principal and Examination Officer. A set is approved or sent back as a whole, and sending it back requires a written reason.'], article: 'approving-question-sets' },
  { id: 'questions-to-paper', group: 'examinations', question: 'How do approved questions enter an examination paper?', answer: ['The examination office opens the examination and selects Compose papers. A paper is created for every subject and class with enough approved questions. A subject without enough is named and skipped.'], article: 'papers-schedule-publish', audience: ['principal', 'vice_principal', 'exam_officer'] },
  { id: 'create-exam', group: 'examinations', question: 'How do I create an examination?', answer: ['Open the examination from the Examinations list and follow its steps in order: Compose papers, Schedule examination, then Publish. Publishing is blocked until every paper has a timetable slot and a sitting window.'], article: 'papers-schedule-publish', audience: ['principal', 'vice_principal', 'exam_officer'] },
  { id: 'timetable', group: 'examinations', question: 'How does the timetable work?', answer: ['In Timetable, set the first and last day of sitting and select Generate. Papers are placed on school days and a class never sits two papers at once. You can adjust one paper with Save slot, and Notify class teachers sends each class teacher their timetable.'], article: 'exam-timetable' },
  { id: 'invigilators', group: 'examinations', question: 'How are invigilators assigned?', answer: ['In Invigilation, the office selects Create invigilation schedule and EduCBT assigns everyone automatically, spreading the load. A subject teacher never invigilates their own paper, and nobody is placed in two halls at once unless the office overrides it for a CBT hall.'], article: 'invigilation-schedule', audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'] },
  { id: 'active-exam', group: 'examinations', question: 'What happens during an active examination?', answer: ['Invigilators open Test/Exam Sessions and select Watch to see each candidate\'s state, answered count and time left. They can give one candidate or the whole hall extra time, with a reason, and force-submit a candidate who leaves.'], article: 'test-and-exam-sessions', audience: ['principal', 'vice_principal', 'exam_officer', 'teacher'] },
  { id: 'reattempt', group: 'examinations', question: 'Can a student sit a paper again?', answer: ['Yes, if a session ended unfairly. The Principal, Vice Principal or Examination Officer can grant a reattempt with a reason. It clears the earlier answers and score.'], article: 'test-and-exam-sessions', audience: ['principal', 'vice_principal', 'exam_officer'] },
  { id: 'marking', group: 'examinations', question: 'How does marking work?', answer: ['Objective questions are marked automatically. Written (theory) answers appear in the teacher\'s Marking page for their subjects; the teacher enters a mark up to the question\'s maximum and selects Award. The exam office sees progress for the whole school in Marking Status.'], article: 'marking-written-answers' },

  // Teachers
  { id: 'record-scores', group: 'teachers', question: 'How do I record CA scores?', answer: ['Open Record scores, choose your class and subject, enter each student\'s scores and select Save scores. Leave a box empty for a student you have not marked, because blank is not zero.'], article: 'recording-ca-scores', audience: ['teacher'] },
  { id: 'cant-edit-scores', group: 'teachers', question: 'Why can I no longer change a score?', answer: ['Once the class\'s results are reviewed, published or locked, score entry is closed. The Principal has to reopen the results first.'], article: 'how-results-are-published', audience: ['teacher'] },
  { id: 'no-classes', group: 'teachers', question: 'Why do I have no classes or subjects?', answer: ['Teachers only see what the school office has assigned to them under Staff. Ask the office to assign you as a subject teacher or class teacher.'], article: 'cannot-see-a-feature', audience: ['teacher'] },
  { id: 'remarks', group: 'teachers', question: 'Where do I set report card remarks and my signature?', answer: ['Class teachers have Remarks and Signature in their menu. If you do not see them, you are not assigned as a class teacher.'], article: 'report-cards', audience: ['teacher'] },

  // Students and parents
  { id: 'student-paper', group: 'students', question: 'Where do I find my exam?', answer: ['On your Dashboard under Your papers. Select Start, or Resume if you began already. Only subjects you are registered for appear, and a paper can only be started inside its sitting window.'], article: 'what-students-see', audience: ['student'] },
  { id: 'student-results', group: 'students', question: 'How do I see my results?', answer: ['Open My results. Results appear only after the Principal has published them for the term.'], article: 'what-students-see', audience: ['student'] },
  { id: 'parent-results', group: 'students', question: 'How does a parent see a child\'s results?', answer: ['Open My children, find the published term under your child, and select Download. If no children appear, or results are not shared with your account, contact the school office.'], article: 'what-parents-see', audience: ['parent'] },
];
